### ISSUE TITLE
Git avec une clef SSH associée au profil

### ISSUE THREAD

**Issue by raphaeleadjerad** [InseeFrLab/onyxia-ui#102]
Merci pour l'infrastructure, elle est très bien.
Est-il possible de s'ajouter une clef SSH depuis "mon compte" pour giter depuis la console dans Jupyter plus aisément ?

**Comment by fcomte** [comment]
Nous pouvons faire cela techniquement.
Néanmoins donner une clé ssh privée à une plateforme centralisé présente quand même fort surtout si c'est celle est utilisé pour des repos github.com ou gitlab.com 
Pourquoi ne pas faire du https plutôt que ssh ?

**Comment by raphaeleadjerad** [comment]
Pas de problème, je comprends. C'était simplement pour ne pas à avoir à rentrer user et mdp à chaque push, mais https me convient très bien.

**Comment by fcomte** [comment]
on peut sans doute pré-configurer le user git..et activer le cache du mot de passe pour un temps donné

**Comment by raphaeleadjerad** [comment]
D'accord, je vais regarder cela. Merci

**Comment by NicoLaval** [comment]
Feat is ready!

You can now edit overall git credentials cache duration in my account page:

![image](https://user-images.githubusercontent.com/30119477/80360853-4307d680-8880-11ea-8a97-616f60bc977b.png)

By default, 0 means you don't want credentials cache.

You can also define a one shot git credentials cache duration in your contract:

![image](https://user-images.githubusercontent.com/30119477/80360460-ae9d7400-887f-11ea-95ec-6d7349672174.png)

When you start your service, you will be able to fill your credential once and have benefits of git credentials cache time you set!
