### ISSUE TITLE
Reinit configuration button may be too confusing

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-ui#114]
A recent and great feature generates a quicklink that users can use to deploy again later with the same configuration : 
![image](https://user-images.githubusercontent.com/3159134/80240699-9ac8f680-8662-11ea-8797-f4b51663175f.png)

This feature comes with a button to let the user reset the configuration back to default but this button uses the same color's scheme as the "deploy service" button. 
The user may be confused and click by mistake on the reset configuration button instead of the deploy button. I suggest we use something more alerting like red or yellow but any suggestion is welcome :)  

Additionnaly, any design improvement and internationalization is obviously also welcome on this page :smiley:

**Comment by fcomte** [comment]
I think this feature should be in advanced feature...
With the development of history and autocomplemention of each contracts, there will be a nearly no case to see this link

**Comment by olevitt** [comment]
Fixed by 596ddc0f5d289679b4895de9b7b69f30b1c627e9
