### ISSUE TITLE
regression on self-service details

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#118]
When we access to detailed self-services, URLs are not displayed.
It's a big regression because secondary url are never display elsewhere.
 
![image](https://user-images.githubusercontent.com/48868412/80701771-35508c00-8ae0-11ea-9ce2-499f3eaa6d52.png)

**Comment by olevitt** [comment]
This is now tracked by #120 (and should be fixed in today's `0.2` release
