### ISSUE TITLE
Username and password for rStudio service

### ISSUE THREAD

**Issue by RupertOnGithub** [InseeFrLab/onyxia-ui#129]
When you want  to connect to the RStudio service, it is not obvious that the username is "rstudio" and that the password can be found in the "Mon compte" section.

This should be explained somewhere on the "RStudio Sign in" form.

**Comment by olevitt** [comment]
Hi,

Thanks for this feedback.  
Onyxia has no control over the `Rstudio sign in form` as services are defined in catalogs which are independant from Onyxia (e.g, Rstudio contract is defined here : https://github.com/inseefrlab/universe-datascience). And even there, I don't think we have easy control over the content displayed as it depends on the official Rstudio docker images.  

I suggest we add support in `onyxia-ui` for pre & post install instructions. Then catalog maintainers would just have to add a message indicating the user is `rstudio`.  
Something like :  
* During service configuration, pre-install notes would be displayed  
* When the user creates the service, post-install notes would be displayed

The UI design choices are up to discussion and PR are obviously welcome if anyone feels like implementing this.  

Note : we will probably also have to add pre & post install definition server-side  (https://github.com/inseefrlab/onyxia-api)

**Comment by olevitt** [comment]
`v0.3` will be released soon `(TM)` and will display `post-install` instructions :)
