### ISSUE TITLE
modify icon of the main grafana dashboard on the foot page

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#138]
We should not use the grafana icon but the monitoring one also present in JS here

![image](https://user-images.githubusercontent.com/48868412/82817312-148c1400-9e9d-11ea-8f7c-a7ebaddb381d.png)

**Comment by olevitt** [comment]
We could also change the chat icon which at the moment uses the rocket-chat icon even if the chat is not a rocket one
