### ISSUE TITLE
add prometheus metrics on bucket usage

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#141]
In the new release of minio, usage counts about each bucket is reported.
Available grafana graph are here :

https://grafana.lab.sspcloud.fr/d/PhCwEJkMz/minio-user?orgId=1&var-username=tm8enk

We should add a monitoring link on each bucket cards.

**Comment by olevitt** [comment]
This feature will be added in v0.3 which will be released Soon (TM).
