### ISSUE TITLE
show the name of an application inside a group of apps

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#153]
This is not a good UX

![image](https://user-images.githubusercontent.com/48868412/84295862-6f836380-ab4b-11ea-9e2e-4fd5e1a67712.png)

**Comment by olevitt** [comment]
Thanks for this feedback !  
This should be fixed in `v0.3` which will be released Soon `(TM)`.  

Note that we opted for a fix server-side.
