### ISSUE TITLE
inject VAULT_TOP_DIR and VAULT_MOUNT

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#166]
We need to inject some values into catalog in accordance to

```
        "mount": {
          "description": "mount of the v2 secret engine",
          "type": "string",
          "x-form": {
            "value": "{{vault.VAULT_MOUNT}}"
          }
        },
        "directory": {
          "description": "top level directory",
          "type": "string",
          "x-form": {
            "value": "{{vault.VAULT_TOP_DIR}}"
          }
        }
```

**Comment by garronej** [comment]
It is already the case for `vscode`, those values are made available as environment variable if the user fills them up before launching the service:  

![image](https://user-images.githubusercontent.com/6702424/93244975-d471d980-f78a-11ea-91fa-6551fa3be9c9.png)
[maranthon.json.mustache](https://github.com/InseeFrLab/Universe-Datascience/blob/master/repo/packages/V/vscode/0/marathon.json.mustache)

Do you mean that we should provide good defaults like `onyxia-kv` for the mount point?  
Or do you mean that we should be able to inject those values in other services like Jupyter?  
If so then shouldn't it be an issue for [Universe-Datascience](https://github.com/InseeFrLab/Universe-Datascience)?

**Comment by fcomte** [comment]
Yes I mean that we should provide good defaults like `onyxia-kv` for the mount and `idep` for top level dir.
