### ISSUE TITLE
RapidsAI service doesn't start on internal server / Doen't have GPU on external server

### ISSUE THREAD

**Issue by haixuanTao** [InseeFrLab/onyxia-ui#173]
It seems that i can't start RapidsAI services in internal server. The loading animation never disappear.

For the external server, the service does boot up, but no GPU can be found.

### Reproduction

Type the following in a terminal:
```
nvidia-smi
```

![no device found](https://user-images.githubusercontent.com/22787340/95220473-cdbd0c00-07f6-11eb-8cfb-1789a9b0e65b.PNG)

**Comment by fcomte** [comment]
this issue is for https://github.com/InseeFrLab/Universe-Datascience

For the external plateforme you should modify reserved gpu before launching the service.
For the internal we face some network issues to access external ressource

**Comment by haixuanTao** [comment]
I opened a pull request https://github.com/InseeFrLab/Universe-Datascience/pull/44  to put the default GPU to 1 in all services.

I think most user expect the default to be as such, but open for discussion.
