### ISSUE TITLE
support for number property in charts

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#195]
This helm contracts does not work because of a number type in a property.

https://github.com/InseeFrLab/helm-charts-datascience/blob/master/charts/blazingsql/values.schema.json

If I don't modify the default values  : 
`nvidia.com/gpu: 0`

If I modify the default values  : 
`nvidia.com/gpu: "1"`

With helm this is failing
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
blazingsql:
- resources.limits.nvidia.com/gpu: Invalid type. Expected: number, given: string
```

**Comment by garronej** [comment]
✅
