### ISSUE TITLE
Ajouter une suggestion boto pour les utilisateurs de S3

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/onyxia-ui#211]
Dans la page https://datalab.sspcloud.fr/account, dans la partie `Identifiants Minio (S3)`, il y a une suggestion pour python basée sur s3fs. Il serait utile de fournir la suggestion équivalente pour les utilisateurs de `boto3`.

Comme je ne sais pas où je devrais le mettre dans un fork, je vous propose ici le code qui fonctionne:

```python
import boto3
s3 = boto3.client("s3",endpoint_url = "https://minio.lab.sspcloud.fr",
                  aws_access_key_id= KEY_ID, 
                  aws_secret_access_key= SECRET_ACCESS, 
                  aws_session_token = TOKEN_HERE)
```

**Comment by garronej** [comment]
Très bien ça marche

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/112973253-681c5d80-9151-11eb-8624-9572e195b1f7.png)
