### ISSUE TITLE
Minio identifiants scripts with spaces

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia-ui#220]
There is is multiple scirpts generate to configure environment variables some spaces that make the script unusable.

![image](https://user-images.githubusercontent.com/63847345/113107805-9d35b800-9204-11eb-9dd1-4cb472080e24.png)

for instance,
* environment variables script => with export VAR= value should be export VAR=value
* mc client : export MC_HOST_minio => with extraspaces at the end

**Comment by garronej** [comment]
Fixed in v0.7.21
