### ISSUE TITLE
Display the custom name (filled out at the services config step) on My Services page 

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/onyxia-ui#226]
## Custom name filled out at the services config step
<img width="1163" alt="Capture d’écran 2021-04-09 à 18 00 37" src="https://user-images.githubusercontent.com/62331119/114385029-c43ea300-9b8f-11eb-9246-978bb9d11490.png">

## The service display on My Services page
Without the custom name in the title (at the moment with a complex and non recognizable name)

<img width="378" alt="Capture d’écran 2021-04-09 à 18 00 57" src="https://user-images.githubusercontent.com/62331119/114385040-c6a0fd00-9b8f-11eb-8988-b16ca06e917d.png">

**Comment by garronej** [comment]
@insee-unissi Done 😊 

![image](https://user-images.githubusercontent.com/6702424/114638716-927f2680-9ccc-11eb-958a-c7c56cd733e5.png)
