### ISSUE TITLE
Use case : generate script for minio

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#35]
The implementation is not clear. User could believe that they should do this configuration inside containers in the datalab. But in fact they only need this configuration for outside access because all containers are already configured

Maybe a label containing the idea "access minio from outside" should clarify where to use this manual configuration

**Comment by jfeudeline** [comment]
Hello Fréderic,
I'm not sure to understand the issue. What are the real use cases of these scripts if they're not useful inside containers in the datalab ,

**Comment by fcomte** [comment]
I think the main usage of theses scripts is to help users to exchange data with S3 from their laptop.. (both to upload data and download results)

Playing with data inside the lab will be more integrated and they can skip the setting of S3 credentials.
