### ISSUE TITLE
env-config.js should not be cached

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-ui#47]
`env-config.js` is included as a script in `index.html`. It contains the whole app configuration which may change when the app is redeployed.  
This file should not be cached (and at the moment it is as any js file would).  

This can either be done client-side (apparently by appending fake get parameters to trick the browser like `<script src="env-config.js?v=42" />`) or server-side (by changing the nginx conf).  

Not sure which one is best ?

**Comment by NicoLaval** [comment]
It seems to be possible to disable cache file by file, so for this one, we can update the `public/index.html` with
`<script src="%PUBLIC_URL%/env-config.js" content="no-cache"></script>`
Seems to do the stuff?

**Comment by olevitt** [comment]
can't find any documentation on `content="no-cache"` for `script tag`. Have you found any ?

**Comment by NicoLaval** [comment]
Seems to be only a meta tag attr :(
