### ISSUE TITLE
Add a "enable beta features" switch button

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-ui#56]
Hello,

We may need to beta test some features that are not fully production-ready.  
At the moment, some of thoses features are "hidden" and people need to know the exact URL to access them.  
I know of at least two of them at the moment :  
* Accessing test catalogs that are sent by the `API` but not displayed in the UI  
* Accessing the `my secrets` page (vault integration which is still a Work In Progress)  

We could add a switch button in my account (or somewhere else ?) to let advanced users enable beta features. The beta opt-in choice would be stored client-side (for example in application storage).  
Users that have opted-in would see the features without restrictions (ie my-secrets item to the menu, display the test catalogs ...), users that opted-out would not see them at all.

**Comment by NicoLaval** [comment]
Redux store seems to be the right place to persist this information.
Switch button will update the entry, and components that need this information would access to the entry through container

**Comment by olevitt** [comment]
@NicoLaval : downside of storing it exclusively in the redux store is that if will be lost on page refresh / reload.  
I think local storage + redux would be better, wouldn't it ?

**Comment by NicoLaval** [comment]
Obv, if you want to keep it even during refreshs, local storage could be a nice solution (in this case, no redux need, it would only give code complexity & duplication of information)

**Comment by olevitt** [comment]
Solved by 2a6d1bd4a48445efccf7dba4e0b6cc681490bbd6
