### ISSUE TITLE
Strange design behavior of buttons in Dialog

### ISSUE THREAD

**Issue by mpagels** [InseeFrLab/onyxia-ui#7]
Hey, I just played around in your deployed Storybook and I noticed some flickering when I'm checking the checkbox in the `Dialog` story. See GIF attached. I was just wondering if this is intended?

![2021-07-27-12-45-08](https://user-images.githubusercontent.com/54703643/127142554-e32139ac-6c0b-4506-a348-996cddfe36b8.gif)

I'm on `Win10` and used `Firefox` and also checked with `Firefox Dev Edition`.

Cheers.

**Comment by garronej** [comment]
Thank for reporting.  
The buttons are measuring themselves to always have perfectly round corner no matter the size of the content.  
There is obviously a problem with how this approach is implemented.   
Thank you for taking the time to reach out!

**Comment by mpagels** [comment]
No problem. Happy to help. You're welcome.

**Comment by garronej** [comment]
Fixed thx!

**Comment by garronej** [comment]
And btw what do you use to make a gif out of your screen capture?

**Comment by mpagels** [comment]
> And btw what do you use to make a gif out of your screen capture?

I recorded a `mp4` with this awesome free GitHub project [Captura](https://github.com/MathewSachin/Captura) and then resized it a bit with `Adobe Premiere Pro` and after that I exported it as an `Animated Gif`.
![grafik](https://user-images.githubusercontent.com/54703643/127645438-e373ca8c-fc32-4b80-a9ae-6085968980e6.png)

**Comment by garronej** [comment]
Ok thanks! 👍🏻 👍🏻
