### ISSUE TITLE
have a button to delete all user services

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/onyxia-ui#83]
On page /my-lab/mes-services we need a button that deletes all services. Of course it also needs a confirmation page.

**Comment by NicoLaval** [comment]
Button is to create into `servicetoolbar.component`.
`dialog-confirm.component`  can be used to display confirmation alert.

Is there an API endpoint to delete all user services or do you have to loop on an unitary one ?

**Comment by olevitt** [comment]
At the moment there is no "delete all" API endpoint but it makes sense to add one (I dislike the idea of iterating over all services to delete them one by one)
