### ISSUE TITLE
luncher page is hanging

### ISSUE THREAD

**Issue by Loumy** [InseeFrLab/onyxia-ui#83]
On the page launcher, in IDE section, after choose a product in the catalog, the page hang.
https://XXXXX/launcher/ide/jupyter-python

Console error :
`main.7fd50f70.js:2 Uncaught (in promise) Error: Wrong assertion encountered: "s3/secretAccessKey has render: "password" and it's not supported"`

**Comment by garronej** [comment]
HI @Loumy, this is the Design system repo.  
The repo you're looking to submit PR is https://github.com/InseeFrLab/onyxia-web  
Anyway, what version of onyxia are you running.  
@ddecrulle Is it solved in the current version? Seems like now we only have a warning for unknown field render am I right?

**Comment by Loumy** [comment]
Thanks, I see. As I was thinking about a JS issue I posted it here.

ATM I haven't S3 and Vault enabled

my version :
    Image:          inseefrlab/onyxia-web:2.1.10
    Image ID:       docker.io/inseefrlab/onyxia-web@sha256:46a1e4679663364cecd65be3b8c8e6cd9ccd7523a6c860489bcced39c530927b

    Image:          inseefrlab/onyxia-api:latest
    Image ID:       docker.io/inseefrlab/onyxia-api@sha256:10f71f12c2fa626dbae5aca0c7118f64a0afdc2ab2a3f89f6e938b51a710fa8e

**Comment by Loumy** [comment]
Work on "latest" on onyxia-web

**Comment by garronej** [comment]
Great thanks for the feedback
