### ISSUE TITLE
user with no self service have a bad UX

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#88]
When a user has no more self service , he lose his toolbar with the + button...
We should keep it

**Comment by olevitt** [comment]
For anyone wanting to work on this, the branch `refactor-services` displays the corresponding component as a story in storybook so it's a lot easier to debug and solve this issue.

**Comment by NicoLaval** [comment]
We should only have the + button, not the four?

**Comment by olevitt** [comment]
I think so yeah. `+` should always be there. Other should be conditional to the number of services being >= 1. What do you think ?
