### ISSUE TITLE
add formations

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#92]
We should create a new top level component to list available formations for users.
All formations are simple json file like : 

`{
    "id": "python onyxia",
    "title": "Python sur le datalab onyxia",
    "description": "Formation en python",
    "maintainer": "Insee",
    "modules": [
         {
            "title" : "Jupyter",
            "description": "Decouverte de l'environnement Jupyter",
            "deploiement" : "https://spyrales.sspcloud.fr/my-lab/catalogue/inseefrlab-datascience/jupyter/deploiement"
        },
        {
            "title" : "S3",
            "description": "Decouverte de S3",
            "deploiement" : "https://spyrales.sspcloud.fr/my-lab/catalogue/inseefrlab-datascience/jupyter/deploiement"
        }
    ]
}
`

Idealy the list of formations come from an  environnement variable.

**Comment by JulietteS** [comment]
It would be relevant to align with schema.org course scheme (https://schema.org/Course and add other information such as info on copyright, licence and estimated time of achievement, prerequisite (allowing to link formations with each other). 
Does the module structure really make sense?

A flat version would be: 


{
    "courseCode": "Jupyter sur Onyxia",
    "name" : "Jupyter dans le datalab",
    "abstract": "Decouverte de l'environnement Jupyter et de son intégration dans le datalab.",
    "timeRequired": "PT30M",
    "author": "Fred",
    "contributor": "Olivier",
    "copyrightHolder": "Insee",
    "copyrightYear": "2020",
    "creativeWorkStatus": "Published",
    "inLanguage": "fr",
    "learningResourceType": "python notebook",
    "licence": "CC BY-SA 2.0 FR",
    "version": "1.0",
    "image": "https://fr.wikipedia.org/wiki/Jupyter#/media/Fichier:Jupyter_logo.svg",
    "deploiement": "https://spyrales.sspcloud.fr/my-lab/catalogue/inseefrlab-datascience/jupyter/deploiement"
   },
{
    "courseCode": "S3 en python",
    "name": "S3 en python",
    "abstract": "Découverte du stockage objet S3, de son utilisation dans un notebook Jupyter",
    "coursePrerequisites" : "Jupyter sur Onyxia",
    "timeRequired": "PT30M",
    "author": "Fred",
    "copyrightHolder": "Insee",
    "copyrightYear": "2020",
    "creativeWorkStatus": "Draft",
    "inLanguage": "fr",
    "learningResourceType": "python notebook",
    "licence": "CC BY-SA 2.0 FR",
    "version": "1.0",
    "deploiement": "https://spyrales.sspcloud.fr/my-lab/catalogue/inseefrlab-datascience/S3/deploiement"
}

**Comment by fcomte** [comment]
I like the idea to align.
I think we need to keep metadata for a list of course.
We can use the course scheme for what I called modules.
