### ISSUE TITLE
css broken

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-ui#96]
![image](https://user-images.githubusercontent.com/48868412/79200941-8b160a80-7e37-11ea-9aa6-f27c1aa0d4c8.png)

**Comment by olevitt** [comment]
Already fixed by 3c9bb2b981b675420b329abcc087f6ba71365c98

**Comment by fcomte** [comment]
![image](https://user-images.githubusercontent.com/48868412/79201296-23ac8a80-7e38-11ea-8a1e-6da771600eaf.png)
